### ISSUE TITLE
升级到Hexo4.0.0后生成报错

### ISSUE THREAD

**Issue by ACANX** [AlynxZhou/hexo-theme-aria#30]
# I Have Done Those and Need to Create a New Issue / 我确定我已经做过了下面这几步并确实需要创建一个新 Issue

- [ ] Yes, I already updated my theme to the newest version as [docs](https://github.com/AlynxZhou/hexo-theme-aria#update-theme) and cleaned cache before testing (`hexo clean && hexo s`). / 是的，我已经按照 [文档](https://github.com/AlynxZhou/hexo-theme-aria/blob/master/README.zh_CN.md#%E6%9B%B4%E6%96%B0%E4%B8%BB%E9%A2%98) 把我的主题更新到最新版本了并在测试之前清除了缓存（`hexo clean && hexo s`）。
- [x] Yes, I already read [Hexo Docs page](https://hexo.io/docs/). / 是的，我已经查阅过 [Hexo 文档](https://hexo.io/zh-cn/docs/index.html) 了。
- [ ] Yes, I already verified I found a theme problem, not a Hexo problem or because of my lack of Markdown usage and Hexo usage. / 是的，我已经确定我发现了一个主题的问题，而不是 Hexo 的问题或者因为我缺乏对于 Markdown 和 Hexo 用法的了解。
- [x] Yes, I already searched opening issues and not found related issues. / 是的，我查找过了未解决的 issue 并且没有发现类似的。

# Expected Behavior / 预期行为

# Actual Behavior / 实际行为

## Related Pages / 相关页面

# Steps to Reproduce / 重现步骤

1. N/A
2. N/A
3. N/A

# Related Configuration and Code / 相关配置和代码

## Site's `_config.yml` / 站点配置文件

```yml


```

## Theme's `_config.yml` / 主题配置文件

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ACANX
subtitle: 'acanx'
description: 'acanx site'
keywords: 
  - ACANX
  - BCANX
  - canxx
author: John Doe
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://acanx.gitee.io/
root: /Blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing index.html from permalinks

# Directory
source_dir: source
public_dir: Blog
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: aria

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''

```

## Code / 代码

```
PS D:\ProgramCode\Hexo\Blog> hexo g                                                                                                                                                                       INFO  Start processing
INFO  Files loaded in 164 ms
ERROR Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\post.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\post.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
    at Object._prettifyError (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:413:3)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:29:16)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:86)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:84)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:82)
    at createTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:315:9)
    at handle (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:327:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:339:9
    at next (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:9:5)
    at Template.render (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:556:10)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo-renderer-njucks\index.js:22:27
    at Theme._View.View._compiled (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\hexo\index.js:365:21
ERROR Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
    at Object._prettifyError (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:413:3)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:29:16)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:86)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:84)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:82)
    at createTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:315:9)
    at handle (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:327:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:339:9
    at next (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:9:5)
    at Template.render (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:556:10)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo-renderer-njucks\index.js:22:27
    at Theme._View.View._compiled (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\hexo\index.js:365:21
ERROR Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
    at Object._prettifyError (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:413:3)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:29:16)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:86)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:84)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:82)
    at createTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:315:9)
    at handle (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:327:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:339:9
    at next (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:9:5)
    at Template.render (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:556:10)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo-renderer-njucks\index.js:22:27
    at Theme._View.View._compiled (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\hexo\index.js:365:21
ERROR Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\archive.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
    at Object._prettifyError (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:413:3)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:29:16)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:86)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:84)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:82)
    at createTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:315:9)
    at handle (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:327:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:339:9
    at next (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:9:5)
    at Template.render (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:556:10)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo-renderer-njucks\index.js:22:27
    at Theme._View.View._compiled (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\hexo\index.js:365:21
ERROR Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\index.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
Template render error: (D:\ProgramCode\Hexo\Blog\themes\aria\layout\index.njk) [Line 52, Column 42]
  TypeError: path.startsWith is not a function
    at Object._prettifyError (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:36:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:567:19
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:413:3)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:29:16)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:24:86)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:20:84)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:46)
    at eval (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:16:82)
    at createTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:315:9)
    at handle (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:327:11)
    at D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:339:9
    at next (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:280:7)
    at Object.asyncIter (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\lib.js:286:3)
    at Environment.getTemplate (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:321:9)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:637:18), <anonymous>:9:5)
    at Template.render (D:\ProgramCode\Hexo\Blog\node_modules\nunjucks\src\environment.js:556:10)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo-renderer-njucks\index.js:22:27
    at Theme._View.View._compiled (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\ProgramCode\Hexo\Blog\node_modules\hexo\lib\hexo\index.js:365:21
INFO  Generated: atom.xml
INFO  Generated: search.xml
INFO  Generated: index.html
INFO  Generated: archives/index.html
INFO  Generated: fonts/lg.eot
INFO  Generated: fancybox/blank.gif
INFO  Generated: fancybox/jquery.fancybox.css
INFO  Generated: fancybox/jquery.fancybox.js
INFO  Generated: images/avatar.png
INFO  Generated: fancybox/jquery.fancybox.pack.js
INFO  Generated: fancybox/fancybox_overlay.png
INFO  Generated: fancybox/fancybox_loading.gif
INFO  Generated: fancybox/fancybox_loading@2x.gif
INFO  Generated: fancybox/fancybox_sprite@2x.png
INFO  Generated: fonts/lg.svg
INFO  Generated: fancybox/fancybox_sprite.png
INFO  Generated: images/logo.png
INFO  Generated: fonts/lg.ttf
INFO  Generated: fonts/lg.woff
INFO  Generated: archives/2019/11/index.html
INFO  Generated: archives/2019/index.html
INFO  Generated: css/fonts/FontAwesome.otf
INFO  Generated: fancybox/helpers/fancybox_buttons.png
INFO  Generated: css/fonts/fontawesome-webfont.eot
INFO  Generated: css/fonts/fontawesome-webfont.woff
INFO  Generated: js/script.js
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.js
INFO  Generated: css/atom-one-light.css
INFO  Generated: css/atom-one-dark.css
INFO  Generated: fancybox/helpers/jquery.fancybox-buttons.css
INFO  Generated: fancybox/helpers/jquery.fancybox-media.js
INFO  Generated: css/commentjs.css
INFO  Generated: css/comment.css
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.js
INFO  Generated: css/info.css
INFO  Generated: fancybox/helpers/jquery.fancybox-thumbs.css
INFO  Generated: css/custom.css
INFO  Generated: css/header.css
INFO  Generated: css/nav.css
INFO  Generated: css/page.css
INFO  Generated: css/normalize.css
INFO  Generated: css/main.css
INFO  Generated: css/post.css
INFO  Generated: css/footer.css
INFO  Generated: css/reward.css
INFO  Generated: css/solarized-dark.css
INFO  Generated: js/busuanzi.pure.mini.js
INFO  Generated: css/sidebar.css
INFO  Generated: css/solarized-light.css
INFO  Generated: js/clipboard.min.js
INFO  Generated: js/index.js
INFO  Generated: js/lg-hash.min.js
INFO  Generated: js/lg-pager.min.js
INFO  Generated: js/custom.js
INFO  Generated: js/lg-fullscreen.min.js
INFO  Generated: js/lg-zoom.min.js
INFO  Generated: js/lg-thumbnail.min.js
INFO  Generated: css/variables.css
INFO  Generated: js/scrollspy.js
INFO  Generated: js/marked.min.js
INFO  Generated: js/timeago.min.js
INFO  Generated: js/search.js
INFO  Generated: js/util.js
INFO  Generated: css/index.css
INFO  Generated: js/commentjs.js
INFO  Generated: css/lightgallery.min.css
INFO  Generated: css/style.css
INFO  Generated: js/highlight.min.js
INFO  Generated: js/lightgallery.min.js
INFO  Generated: js/jquery.min.js
INFO  Generated: css/images/banner.jpg
INFO  Generated: css/fonts/fontawesome-webfont.ttf
INFO  Generated: css/fonts/fontawesome-webfont.svg
INFO  Generated: js/fontawesome-all.min.js
INFO  Generated: 2019/11/23/hello-world/index.html
INFO  Generated: images/background.png
INFO  76 files generated in 2.47 s
PS D:\ProgramCode\Hexo\Blog>   
```

# Others / 其他

**Comment by AlynxZhou** [comment]
https://github.com/hexojs/hexo-generator-feed/issues/115

我花了两小时研究 Hexo 毫无用处的报错，然后发现 `hexo-generator-feed` 的两行代码打破了兼容性，我还没有想好怎么解决 `hexo.config.feed.path` 是个数组的情况（我的说明文档里建议的是用一个字符串，谁知道它给改了），建议先删掉 `hexo-generator-feed`，等我上面那个 issue 有结果了再说。

**Comment by AlynxZhou** [comment]
他们改了，但我不确定什么时候发 release，等等吧。
